### ISSUE TITLE
CPK hex codes.

### ISSUE THREAD

**Issue by joshhales1** [AlexGustafsson/molecular-data#2]
A few of the CPK hex codes are malformed. Fluorine for example is `9e+51` and Magnesium is just `8`.

**Comment by AlexGustafsson** [comment]
@JayHales thanks for reaching out! If you want to open a pull request with the fixes, you’re more than welcome. Otherwise I’ll try to correct the data as soon as I get the time.

**Comment by joshhales1** [comment]
Yeah, I've been looking through further and found a couple more errors. I'll have a shot at working in this in the next couple of days.

**Comment by joshhales1** [comment]
I made the pull request. Fixed the hex codes. Looks like you parsed the hex codes to an integer at some point and they got interpreted interestingly.

**Comment by AlexGustafsson** [comment]
@JayHales I think that may have been due to how the data was converted to different formats, basically I used whatever converted was available without looking too much into the results as the data was originally for another project altogether.

**Comment by AlexGustafsson** [comment]
Closing as #3 is now merged. Thank you for the contribution!
